### ISSUE TITLE
#if / #endif block inside Makefile.am always executes

### ISSUE THREAD

**Issue by MagaTailor** [ttsiodras/renderer#2]
Found in issue #1, tested on 32-bit distros: Slackware current and Ubuntu 14.04

On a tangent, during autoreconf/automake I'm getting this warning (among others):

```
configure.ac:15: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:15: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
```

**Comment by ttsiodras** [comment]
About the bug:

Indeed, reproduced in my Raspberry PI 2.  The check I am making appears to be non-portable across all Unices....  it does work in my Arch/amd64 (i.e. `MLAA.cc` is not compiled when `--enable-mlaa` is not passed) but it's e.g. ignored in my Raspberry PI 2 (and in @petevine 's Slackware). 
Will update my `configure.ac` and `Makefile.am` to fix it. 

About the warnings:

Yep - all the warnings you see (including that one) come from `lib3ds`'s autoconf file (`lib3ds-1.3.0/configure.ac`). It's an old library, so all sorts of things inside its `configure` are now deprecated... One solution would be to drop it and stick to my own parts (which are up to date) - but I feel bad about dropping functionality to silence build warnings... 

I could try to fix that library's `configure` - but it's not my own, and that will make it... challenging.

**Comment by ttsiodras** [comment]
Can you try it now, @petevine ?

And to make it more interesting, these are the values reported by `make bench` from my Raspberry PI 2 (4 Arm cores for 35$, the world has changed! :-) 

```
$ make bench
make -C src bench
make[1]: Entering directory '/root/tmp/renderer-2.3a/src'
14.9961
14.9921
15.0417
14.9768
15.0146
  Average value: 15.004260
  Std deviation: 0.024886
         Median: 14.996100
            Min: 14.976800
            Max: 15.041700
```

**Comment by MagaTailor** [comment]
Well done, thanks!

Here's my result from Odroid C1: `Average value: 27.766080`
                  and Athlon XP 2.2 GHz: `Average value: 15.504180`

**Comment by ttsiodras** [comment]
Wow, C1 is fast!

My laptop's `Intel(R) Core(TM) i5-3427U` scores 94... The gap is definitely closing (and given price points, I think ARM is already more cost-efficient - I just have to make the renderer distributed, so I can  run it on a cloud of PIs :-)

**Comment by MagaTailor** [comment]
Definitely! All these arm options are getting more and more interesting. I'll be adding the result from my old Athlon XP later for some funny performance per watt comparison :)
